/*
 * Generated by Bluespec Compiler, version 2017.07.A (build 1da80f1, 2017-07-21)
 * 
 * On Fri Sep 21 08:54:38 -03 2018
 * 
 */
extern "C" {
  unsigned int socket_get();
  void socket_put(unsigned int );
}
